### ISSUE TITLE
kibana format

### ISSUE THREAD

**Issue by wallymathieu** [ozzymcduff/ElasticElmah#11]
Should be able to loget in Logstash or kibana format.

**Comment by petterl** [comment]
Any plans to pursuing this? I would love to keep using the package, but we are moving towards using kibana format for some of the logs.

**Comment by wallymathieu** [comment]
I don't have much time to fix this right now, but it should not be hard to fix. 

Perhaps that 
https://github.com/jptoto/log4net.ElasticSearch
has implemented this.

One alternative is to let this library use jptoto/log4net.ElasticSearch since library got few dependencies.

**Comment by wallymathieu** [comment]
Serilog might implement a kibana friendly appender as well.

**Comment by wallymathieu** [comment]
@petterl If any of those alternatives does not solve you problem, your more than welcome to send a pull request!
